//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int IDGioHang { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public int IDUser { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual User User { get; set; }
    }
}
