//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTheThao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public string HinhChinh { get; set; }
        public string HinhPhu1 { get; set; }
        public string HinhPhu2 { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string Size { get; set; }
        public string Size1 { get; set; }
        public string Size2 { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string HangSX { get; set; }
        public Nullable<int> IDDanhMuc { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
    
        public virtual DanhMucSP DanhMucSP { get; set; }
    }
}
